name: Validate
on:
  push:
  pull_request:
#  schedule:
#    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate_hacks:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: HACS Validation
        uses: "hacs/action@main"
        with:
          category: "integration"
